##############################################
# Opening lines (15 full moves / 30 half-moves)
##############################################
def fetch_top_openings():
    """
    Returns a dictionary mapping opening names to a list of SAN moves.
    Each list corresponds to 15 full moves (30 half moves) of mainline theory,
    representing popular lines from top-level play.
    """
    return {
        "Ruy Lopez": [
            "e4", "e5",
            "Nf3", "Nc6",
            "Bb5", "a6",
            "Ba4", "Nf6",
            "O-O", "Be7",
            "Re1", "b5",
            "Bb3", "d6",
            "c3", "O-O",
            "h3", "Nb8",
            "d4", "Nbd7",
            "Nbd2", "Bb7",
            "Bc2", "Re8",
            "Nf1", "Bf8",
            "Ng3", "g6",
            "a4", "exd4"
        ],
        "Sicilian Defense": [
            "e4", "c5",
            "Nf3", "d6",
            "d4", "cxd4",
            "Nxd4", "Nf6",
            "Nc3", "a6",
            "Be3", "e5",
            "Nb3", "Be6",
            "f3", "Be7",
            "Qd2", "O-O",
            "O-O-O", "Nbd7",
            "g4", "b5",
            "g5", "b4",
            "Na4", "Rc8",
            "Kb1", "Nc5",
            "Bc4", "Nfd7"
        ],
        "French Defense": [
            "e4", "e6",
            "d4", "d5",
            "Nc3", "Nf6",
            "Bg5", "Bb4",
            "e5", "h6",
            "Bh4", "O-O",
            "Nge2", "c5",
            "a3", "Bxc3+",
            "bxc3", "Nc6",
            "Qg4", "g6",
            "Bd3", "Ba6",
            "O-O", "Qxd3",
            "Rfe1", "Qxc2",
            "Ng3", "cxd4",
            "cxd4", "Nxd4"
        ],
        "Caro-Kann Defense": [
            "e4", "c6",
            "d4", "d5",
            "Nc3", "dxe4",
            "Nxe4", "Nd7",
            "Ng5", "Ngf6",
            "Bd3", "h6",
            "Nge4", "e6",
            "Nxf6+", "Nxf6",
            "O-O", "Bd6",
            "Re1", "O-O",
            "c3", "Qc7",
            "Bg5", "Rad8",
            "Qd3", "c5",
            "dxc5", "Bxc5",
            "Rad1", "Rd7"
        ],
        "Queen's Gambit": [
            "d4", "d5",
            "c4", "e6",
            "Nc3", "Nf6",
            "Bg5", "Bb4",
            "e3", "O-O",
            "Nf3", "c5",
            "cxd5", "exd5",
            "Bd3", "Nc6",
            "O-O", "Re8",
            "Rc1", "b6",
            "a3", "Ba6",
            "Qe2", "Bxd3",
            "Qxd3", "Qb8",
            "Rfd1", "Rac8",
            "Bf1", "Rxc1"
        ],
        "King's Indian Defense": [
            "d4", "Nf6",
            "c4", "g6",
            "Nc3", "Bg7",
            "e4", "d6",
            "Nf3", "O-O",
            "Be2", "e5",
            "O-O", "Nc6",
            "d5", "Ne7",
            "b4", "a5",
            "Ba3", "axb4",
            "Bxb4", "f5",
            "a4", "Nf5",
            "Nd2", "Nxd4",
            "Qc2", "Qe8",
            "Rab1", "Rf6"
        ],
        "Nimzo-Indian Defense": [
            "d4", "Nf6",
            "c4", "e6",
            "Nc3", "Bb4",
            "Qc2", "O-O",
            "a3", "Bxc3+",
            "Qxc3", "c5",
            "e4", "d5",
            "Bd3", "Nc6",
            "Nf3", "dxc4",
            "Bxc4", "a6",
            "O-O", "b5",
            "Be2", "Bb7",
            "Rfd1", "Qc7",
            "Rd3", "Rad8",
            "Ne5", "Rfe8"
        ],
        "English Opening": [
            "c4", "e5",
            "Nc3", "Nf6",
            "g3", "Nc6",
            "Bg2", "d6",
            "d4", "exd4",
            "Nxd4", "Be7",
            "Nf3", "O-O",
            "O-O", "a6",
            "a4", "Re8",
            "Qc2", "b6",
            "Rd1", "Bb7",
            "b3", "Qc7",
            "Bb2", "Rab8",
            "Rfe1", "Nd4",
            "e3", "Nxf3+"
        ],
        "Italian Game": [
            "e4", "e5",
            "Nf3", "Nc6",
            "Bc4", "Bc5",
            "c3", "Nf6",
            "d4", "exd4",
            "cxd4", "Bb4+",
            "Nc3", "d5",
            "exd5", "Nxd5",
            "O-O", "O-O",
            "Re1", "Be6",
            "Bg5", "f6",
            "Bd3", "Ne7",
            "Qb3", "c6",
            "Nxd5", "cxd5",
            "Rad1", "Re8"
        ],
        "Scandinavian Defense": [
            "e4", "d5",
            "exd5", "Qxd5",
            "Nc3", "Qa5",
            "d4", "Nf6",
            "Nf3", "c6",
            "Bc4", "Bf5",
            "O-O", "e6",
            "Re1", "Bb4",
            "Bd2", "O-O",
            "a3", "Bxc3",
            "Bxc3", "Nbd7",
            "Qd3", "Rad8",
            "Be3", "Qc7",
            "Rxe6", "Nxe4",
            "Qe2", "Rxd4"
        ],
        "Pirc Defense": [
            "e4", "d6",
            "d4", "Nf6",
            "Nc3", "g6",
            "Nf3", "Bg7",
            "Be2", "O-O",
            "O-O", "c6",
            "a4", "b6",
            "Be3", "Bb7",
            "Qd2", "Nbd7",
            "Rad1", "Re8",
            "b3", "Qc7",
            "Rfe1", "Rab8",
            "Bb1", "a6",
            "h3", "Nc5",
            "Bc1", "Rf8"
        ],
        "Modern Defense": [
            "e4", "g6",
            "d4", "Bg7",
            "Nc3", "d6",
            "f4", "Nf6",
            "Nf3", "O-O",
            "Be2", "c6",
            "O-O", "Qc7",
            "a4", "b6",
            "Kh1", "Bb7",
            "Bd3", "a6",
            "Qe1", "Rfe8",
            "Qh4", "exf4",
            "Bxf4", "Nd7",
            "Rf1", "Nf8",
            "Rf2", "Rf8"
        ],
        "Dutch Defense": [
            "d4", "f5",
            "c4", "Nf6",
            "Nc3", "e6",
            "Nf3", "d5",
            "Bg5", "Bb4",
            "e3", "O-O",
            "Bd3", "c5",
            "O-O", "Nc6",
            "a3", "Bxc3",
            "bxc3", "dxc4",
            "Qe2", "Qe7",
            "Rfd1", "Rd8",
            "Ne5", "Rxd4",
            "Bf4", "Nd5",
            "Qc2", "e5"
        ],
        "Vienna Game": [
            "e4", "e5",
            "Nc3", "Nf6",
            "f4", "d5",
            "fxe5", "Nxe4",
            "Nf3", "Bc5",
            "Bb5+", "c6",
            "d4", "Bb6",
            "O-O", "O-O",
            "Qe2", "Qe7",
            "Bxc6", "bxc6",
            "dxe5", "Re8",
            "Qe2", "Qxe7",
            "Rxe7", "Nc3",
            "Rxe7", "Nxa2",
            "Rxd5", "Rxd5"
        ],
        "Scotch Game": [
            "e4", "e5",
            "Nf3", "Nc6",
            "d4", "exd4",
            "Nxd4", "Nf6",
            "Nc3", "Bb4",
            "Nxc6", "bxc6",
            "Bd3", "d5",
            "O-O", "O-O",
            "Bg5", "Re8",
            "Re1", "h6",
            "Bh4", "c5",
            "exd5", "cxd5",
            "Qf3", "Be7",
            "Rad1", "Qd7",
            "Bxf6", "Qxf6"
        ]
    }
