def fetch_top_openings():
    """
    Returns a dictionary mapping Queen’s Gambit variation names to a list of SAN moves.
    Each list corresponds to 15 full moves (30 half moves) of mainline theory.
    The variations provided below are among the most popular and theoretically precise.
    """
    return {
        "QGA (Queen's Gambit Accepted)": [
            "d4", "d5",
            "c4", "dxc4",
            "Nf3", "Nf6",
            "e3", "e6",
            "Bxc4", "c5",
            "O-O", "a6",
            "a4", "Nc6",
            "Qe2", "b5",
            "Bd3", "Bb7",
            "Nc3", "O-O",
            "Rd1", "Qc7",
            "e4", "cxd4",
            "exd5", "Nxd5",
            "Ne5", "Rfd8",
            "Bf4", "Re8"
        ],
        "QGD Orthodox Defense": [
            "d4", "d5",
            "c4", "e6",
            "Nc3", "Nf6",
            "Bg5", "Be7",
            "e3", "O-O",
            "Nf3", "h6",
            "Bh4", "b6",
            "cxd5", "exd5",
            "Bd3", "Bb7",
            "O-O", "Nbd7",
            "Rc1", "c5",
            "Qe2", "Rc8",
            "Rfd1", "Ne4",
            "Bb1", "Nxd4",
            "Bxe7", "Qxe7"
        ],
        "QGD Tarrasch Defense": [
            "d4", "d5",
            "c4", "e6",
            "Nc3", "c5",
            "cxd5", "exd5",
            "Nf3", "Nc6",
            "Bg5", "cxd4",
            "e3", "Nf6",
            "Bd3", "Bd6",
            "O-O", "O-O",
            "Rc1", "Re8",
            "Qe2", "Qa5",
            "Rfd1", "a6",
            "Bxf6", "Qxf6",
            "a3", "Be7",
            "Qd2"
        ],
        "QGD Lasker Defense": [
            "d4", "d5",
            "c4", "e6",
            "Nc3", "Nf6",
            "Bg5", "Be7",
            "e3", "O-O",
            "Nf3", "h6",
            "Bh4", "dxc4",
            "Bxc4", "c5",
            "O-O", "Nc6",
            "a4", "a6",
            "Qe2", "b5",
            "Rd1", "Bb7",
            "Ne5", "Qc7",
            "Nxc4", "Nxe5",
            "Bxe7", "Rxe7"
        ],
        "QGD Cambridge Springs": [
            "d4", "d5",
            "c4", "e6",
            "Nc3", "Nf6",
            "Bg5", "Bb4",
            "e3", "O-O",
            "Nf3", "c5",
            "Rc1", "Nc6",
            "Bd3", "cxd4",
            "exd4", "dxc4",
            "Bxc4", "b6",
            "O-O", "Bb7",
            "Qe2", "Rc8",
            "a3", "Ba5",
            "Rfd1", "Qe7",
            "Bxf6", "gxf6"
        ],
        "QGD Semi-Tarrasch": [
            "d4", "d5",
            "c4", "e6",
            "Nc3", "Nf6",
            "Bg5", "dxc4",
            "e4", "Bb4",
            "e5", "h6",
            "Bh4", "g5",
            "Nge2", "Nbd7",
            "O-O", "Bg7",
            "f4", "O-O",
            "Qe2", "c5",
            "Rfd1", "Qe7",
            "Rd3", "a6",
            "Bf2", "Nxc3",
            "bxc3"
        ],
        "QGD Exchange Variation": [
            "d4", "d5",
            "c4", "e6",
            "Nc3", "Nf6",
            "cxd5", "exd5",
            "Bg5", "c6",
            "e3", "Bb4",
            "Bd3", "O-O",
            "Nge2", "Re8",
            "O-O", "h6",
            "Bh4", "Nbd7",
            "Qe2", "Be7",
            "Rfd1", "a6",
            "Rac1", "Qc7",
            "a3", "Ba5",
            "Bxc2"
        ],
        "QGD Ragozin Defense": [
            "d4", "d5",
            "c4", "e6",
            "Nc3", "Nf6",
            "Bg5", "Bb4",
            "e3", "O-O",
            "Nf3", "c5",
            "Bd3", "dxc4",
            "Bxc4", "Nc6",
            "O-O", "Qe7",
            "a3", "Ba5",
            "Qc2", "Rd8",
            "Rfd1", "b6",
            "Rac1", "Bb7",
            "b4", "a6",
            "Na4"
        ],
        "QGD Chigorin Defense": [
            "d4", "d5",
            "c4", "Nc6",
            "Nc3", "Nf6",
            "cxd5", "Nxd5",
            "e4", "Nxc3",
            "bxc3", "e6",
            "Nf3", "Bd6",
            "Bd3", "O-O",
            "O-O", "Re8",
            "Qe2", "Bg4",
            "Rfd1", "a6",
            "Rac1", "Qe7",
            "f3", "Bh5",
            "Ne5", "Rxe5",
            "Qxh5"
        ],
        "QGD Noteboom Variation": [
            "d4", "d5",
            "c4", "e6",
            "Nc3", "Nf6",
            "Bg5", "Bb4",
            "e3", "O-O",
            "Nf3", "c5",
            "cxd5", "exd5",
            "Bd3", "Nc6",
            "O-O", "Re8",
            "Rc1", "a6",
            "Qe2", "b5",
            "Rac1", "Bd6",
            "Ne2", "Ne4",
            "Bxe7", "Qxe7",
            "f3"
        ]
    }
